# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rest.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("rest.proto", :syntax => :proto3) do
    add_message "EchoMessage" do
      optional :value, :string, 1
    end
  end
end

EchoMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("EchoMessage").msgclass
