# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: hello_world.proto for package 'helloworld'

require 'grpc'
require 'hello_world_pb'

module Helloworld
  module Greeter
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'helloworld.Greeter'

      rpc :SayHello, HelloRequest, HelloReply
      rpc :SayHelloAgain, HelloRequest, HelloReply
    end

    Stub = Service.rpc_stub_class
  end
end
