# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: slightly_more_complex.proto for package 'slightlymorecomplex'

require 'grpc'
require 'slightly_more_complex_pb'

module Slightlymorecomplex
  module UserService
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'slightlymorecomplex.UserService'

      rpc :CreateUser, UserRequest, UserResponse
    end

    Stub = Service.rpc_stub_class
  end
end
