# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: slightly_more_complex.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("slightly_more_complex.proto", :syntax => :proto3) do
    add_message "slightlymorecomplex.User" do
      optional :name, :string, 1
      optional :email, :string, 2
      optional :age, :int32, 3
    end
    add_message "slightlymorecomplex.UserRequest" do
      optional :data, :message, 1, "slightlymorecomplex.User"
    end
    add_message "slightlymorecomplex.UserResponse" do
      optional :message, :string, 1
      optional :created, :int32, 2
    end
  end
end

module Slightlymorecomplex
  User = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("slightlymorecomplex.User").msgclass
  UserRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("slightlymorecomplex.UserRequest").msgclass
  UserResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("slightlymorecomplex.UserResponse").msgclass
end
