# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: reverse.proto for package ''

require 'grpc'
require 'reverse_pb'

module Reverse
  class Service

    include GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'Reverse'

    rpc :Echo, Message, Message
  end

  Stub = Service.rpc_stub_class
end
