# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: http.proto for package ''

require 'grpc'
require 'http_pb'

module Http
  class Service

    include GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'Http'

    rpc :Echo, EchoMessage, EchoMessage
  end

  Stub = Service.rpc_stub_class
end
