# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: auth.proto for package ''

require 'grpc'
require 'auth_pb'

module Auth
  class Service

    include GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'Auth'

    rpc :SecretThing, AuthRequest, AuthReply
  end

  Stub = Service.rpc_stub_class
end
