# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: testing.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("testing.proto", :syntax => :proto3) do
    add_message "testing.HelloRequest" do
      optional :name, :string, 1
    end
    add_message "testing.HelloReply" do
      optional :message, :string, 1
    end
  end
end

module Testing
  HelloRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("testing.HelloRequest").msgclass
  HelloReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("testing.HelloReply").msgclass
end
