# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: testing.proto for package 'testing'

require 'grpc'
require 'testing_pb'

module Testing
  module Greeter
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'testing.Greeter'

      rpc :SayHello, HelloRequest, HelloReply
    end

    Stub = Service.rpc_stub_class
  end
end
